# Generated by Django 5.2.1 on 2025-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicsapp', '0002_adminregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('phones', 'phones'), ('laptops', 'laptops'), ('television', 'television'), ('computers', 'computers'), ('cables', 'cables')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
